# Generated by Django 3.2.9 on 2022-10-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='images',
        ),
    ]
